//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentTable
    {
        public int comment_Id { get; set; }
        public string comment_data { get; set; }
        public System.DateTime comment_time { get; set; }
        public int comment_userID { get; set; }
        public int comment_postID { get; set; }
    
        public virtual PostTable PostTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
