//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikesTable
    {
        public int like_Id { get; set; }
        public System.DateTime like_time { get; set; }
        public int like_userID { get; set; }
        public int like_postID { get; set; }
    
        public virtual PostTable PostTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
