//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<commentTable> commentTables { get; set; }
        public DbSet<LikesTable> LikesTables { get; set; }
        public DbSet<PostTable> PostTables { get; set; }
        public DbSet<projectData> projectDatas { get; set; }
        public DbSet<ProjectsTable> ProjectsTables { get; set; }
        public DbSet<teamMembersTable> teamMembersTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
        public DbSet<GroupPost> GroupPosts { get; set; }
    }
}
