//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectData
    {
        public int srNo { get; set; }
        public int projectID { get; set; }
        public string link { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ProjectsTable ProjectsTable { get; set; }
    }
}
