//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsTable
    {
        public ProjectsTable()
        {
            this.projectDatas = new HashSet<projectData>();
            this.teamMembersTables = new HashSet<teamMembersTable>();
            this.GroupPosts = new HashSet<GroupPost>();
        }
    
        public int project_id { get; set; }
        public int teamLead_id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int post_id { get; set; }
    
        public virtual PostTable PostTable { get; set; }
        public virtual ICollection<projectData> projectDatas { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<teamMembersTable> teamMembersTables { get; set; }
        public virtual ICollection<GroupPost> GroupPosts { get; set; }
    }
}
