//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamMembersTable
    {
        public int srNo { get; set; }
        public int project_id { get; set; }
        public int user_id { get; set; }
        public bool request { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual ProjectsTable ProjectsTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
