//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public UserTable()
        {
            this.commentTables = new HashSet<commentTable>();
            this.LikesTables = new HashSet<LikesTable>();
            this.PostTables = new HashSet<PostTable>();
            this.ProjectsTables = new HashSet<ProjectsTable>();
            this.teamMembersTables = new HashSet<teamMembersTable>();
            this.GroupPosts = new HashSet<GroupPost>();
        }
    
        public int user_Id { get; set; }
        public string user_userName { get; set; }
        public string user_userPassword { get; set; }
        public string user_address { get; set; }
        public string user_phoneNo { get; set; }
        public bool user_type { get; set; }
        public string user_emailid { get; set; }
        public string user_description { get; set; }
        public string user_FullName { get; set; }
        public System.DateTime user_DOB { get; set; }
        public bool user_gender { get; set; }
    
        public virtual ICollection<commentTable> commentTables { get; set; }
        public virtual ICollection<LikesTable> LikesTables { get; set; }
        public virtual ICollection<PostTable> PostTables { get; set; }
        public virtual ICollection<ProjectsTable> ProjectsTables { get; set; }
        public virtual ICollection<teamMembersTable> teamMembersTables { get; set; }
        public virtual ICollection<GroupPost> GroupPosts { get; set; }
    }
}
